name: Build and Push MongoDB Image

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract mongo-express version from Dockerfile
        id: get_version
        run: |
          VERSION=$(grep -m1 '^FROM mongo-express:' Dockerfile | cut -d':' -f2)
          echo "MONGO_EXP_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/mongo-express:latest
            ghcr.io/${{ github.repository_owner }}/mongo-express:${{ env.MONGO_EXP_VERSION }}
